### ISSUE TITLE
MSYS=winsymlinks:nativestrict breaks core symlinks (/dev/fd, etc)

### ISSUE THREAD

**Issue by jliben** [Alexpux/Cygwin#13]
Hi there, 

I'm using msys2 to allow to run shell scripts on windows, which start a java application. This app is creating multiple symlinks to JAVA installation directory, so I decided to enable option MSYS=winsymlinks:nativestrict (which would otherwise result in copying the JDK)

I disovered the issue I'm reporting here when I accidentally deleted /dev/fd and /dev/std{in,out,err}. Those files are recreated by the /etc/profile postinstall scripts.

If you ls -l on a regular msys2/cygwin install, you'll see that they are symlinks to another symlink (/proc/self/...)

```
$ ls -l /dev/{fd,std*}
lrwxrwxrwx 1 jliben Domain Users 13 16 nov.  16:37 /dev/fd -> /proc/self/fd
lrwxrwxrwx 1 jliben Domain Users 15 16 nov.  16:37 /dev/stderr -> /proc/self/fd/2
lrwxrwxrwx 1 jliben Domain Users 15 16 nov.  16:37 /dev/stdin -> /proc/self/fd/0
lrwxrwxrwx 1 jliben Domain Users 15 16 nov.  16:37 /dev/stdout -> /proc/self/fd/1
```

But if you erase those files, modify the msys2_shell.bat file to:
```
set MSYS=winsymlinks:nativestrict
```

... you'll get the following output:
```
$ ls -l /dev/{fd,std*}
lrwxrwxrwx 1 jliben Domain Users 14 16 nov.  16:20 /dev/fd -> /proc/10264/fd
lrwxrwxrwx 1 jliben Domain Users 16 16 nov.  16:20 /dev/stderr -> /proc/13540/fd/2
lrwxrwxrwx 1 jliben Domain Users 16 16 nov.  16:20 /dev/stdin -> /proc/13504/fd/0
lrwxrwxrwx 1 jliben Domain Users 16 16 nov.  16:20 /dev/stdout -> /proc/14092/fd/1
```

which makes some things disfunctional, because the symlinks have been created to the actual files at the time of running the shell the first time.

I am not really familiar with the way the different symlinks are being handled, so I'm unable to propose a patch (I actually don't understand where in the cygwin codebase this is handled) but I gather that those files should actually be kept as "regular cygwin symlinks", i.e files with the magic cookie and the path to the target stored inside.

Do you think there is something that could be done to keep on handling those special files as cygwin  symlinks ?

**Comment by jliben** [comment]
Of course I found a simple workaround for my specific case, which is to run the /etc/postinstall scripts first, without enabling the native symlinks feature.

**Comment by elieux** [comment]
We could call `MSYS="${MSYS//winsymlinks/}" ln -sf ... ...` instead in the post-install scripts. @Alexpux, @mingwandroid, any objections before I make a pull request?

**Comment by mingwandroid** [comment]
sounds reasonable @elieux

**Comment by jliben** [comment]
I'm not really sure that would change anything: MSYS deals with symlink creation by **copying** the files. 

I believe the explanation is given by @Alexpux in the [wiki page] (http://sourceforge.net/p/msys2/wiki/How%20does%20MSYS2%20differ%20from%20Cygwin/):
``` Replacement of symlinks with copying, so that Windown programs don't trip up on these files.  ```

So this would probably need some patching of msys core, so that symlinks get created as 'cygwin' links under some special mount points, such as /dev or /proc. That's actually the behaviour of msys2 when you start the shell without winsymlinks option.

Not sure if I'm really clear though ... to summarize:
 - starting msys2 shell without winsymlinks: the creation of /dev entries creates cygwin symlinks
 - starting msys2 shell with winsymlinks option: the creation of /dev/entries creates windows symlinks, which is wrong

**Comment by elieux** [comment]
As you wrote, copies are *not* created when linking to `/dev` or `/proc`, so we only need to override the `winsymlinks` setting when creating these "system" symlinks, which is exactly what I proposed.

I don't think we need to change to runtime to decide this automatically. If someone really wants to create NTFS symlinks targetting `/dev`, why not?

**Comment by elieux** [comment]
So it seems it will be patched in the runtime nevertheless, see https://cygwin.com/ml/cygwin/2015-11/msg00252.html. I will therefore not create any patches for our scripts.

Let's close this issue once the change hits MSYS2 runtime and is verified to work.

**Comment by jliben** [comment]
Oh this is good news that the issue is identified at cygwin level.

Thanks for looking this up in the cygwin mailing list :)

As you said, let's wait for this to be fixed and reach the MSYS2 runtime. I'm closing the issue.
