### ISSUE TITLE
Running node from vim complains about tty

### ISSUE THREAD

**Issue by timmyL17** [Alexpux/Cygwin#21]
Hi,

I'm not sure if this is the correct place to report this. Feel free to tell me a more appropriate place.

I'm trying to use the syntastic plugin for vim for syntax checking of files. For javascript, I'm trying to use jshint, which uses node.js. When I run node from the msys2 terminal, everything seems fine:

>$ node -p -e "Boolean(process.stdin.isTTY)"
>true

However, when I try to run node from inside vim:

>:echo system('node')

It prints the error `stdin is not a tty` . So the syntax checking through syntastic won't work correctly.

When I was using cygwin 2 months ago, calling node from inside vim worked perfectly. I switched to msys2 because it was faster and smaller than cygwin. Is there a fundamental difference between the two that is causing this issue?

Thanks.

**Comment by Alexpux** [comment]
Right place to report this is https://github.com/Alexpux/MSYS2-packages
Cygwin still use vim 7 as I remember, maybe some changes in 8 version that break this.

**Comment by timmyL17** [comment]
Thanks, I moved it over there.
https://github.com/Alexpux/MSYS2-packages/issues/705

This has been happening in msys2 for over a month, so I don't think it is due to the recent version 8 update this week. I just haven't gotten around to reporting it until now.
