### ISSUE TITLE
How to make Visual Studio tools available?

### ISSUE THREAD

**Issue by bardware** [Alexpux/Cygwin#25]
I used to open a `cmd`, call `C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat` then switched to `msys2` dir and start the command line using `msys2_shell.bat`.  In msys2 I had the Visual Studion tools like `cl` available.
Now, after you have switched to `msys2_shell.cmd` a new shell session is initiated wenn msys2 is started. `cl` is not available in msys2. 

What do I have to do to make `cl` or `nmake` available in msys2?

**Comment by forgottenswitch** [comment]
Does this work? `msys_with_vars.bat`:
```
call C:\path\to\vcvarsall.bat
start C:\msys\msys2.exe %1 %2 %3 %4
```
Then MSYS should have all the environment variables defined by `vcvarsall.bat`.
To get rid of a console window popping up, create a shortcut, and set its "Run: Minimzed" property.

**Comment by bardware** [comment]
I allways had in mind I opened this ticket but forgot where. Thanks for your reply.

I studied `msys2_shell.cmd` in the meantime and found a command line switch there. 
I now open `cmd` call `vcvarsall.bat`, change to msys2 directory and then 
```
msys2_shell.cmd -mingw64 -use-full-path
```
This maintains the path information through some magic.
