### ISSUE TITLE
error while loading shared libraries: ?: cannt open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ajneu** [Alexpux/Cygwin#27]
```bash
$ which cmake
/mingw32/bin/cmake

$ cmake
C:/msys32/mingw32/bin/cmake.exe: error while loading shared libraries: ?: cannt open shared object file: No such file or directory
```

My original msys was in `C:/msys32/`, as can be seen above.

I even reinstalled whole msys in `C:/msys32_new/` from scratch. Still does not work.
But during installation, I had windows-wide environment variable PATH set to my previous msys
`C:\msys32\mingw32\bin;C:\msys32\usr\bin`

Maby this stuffed up the reinstall??

What can I do?
Thanks.

**Comment by Alexpux** [comment]
This is wrong place for issue atr all. You must use MINGW-packages or MSYS2-packages depends on program.
Also this problem was reported and fixed. Try update packages.
