### ISSUE TITLE
Some commands (diff/cmp) not found in /usr/bin

### ISSUE THREAD

**Issue by neolib** [Alexpux/Cygwin#31]
I installed msys2-i686-20161025.exe and did pacman -Syu and pacman -Su as described in the homepage, but it seems there are some commands missing from /usr/bin, e.g. diff and cmp. This causes some configure scripts fail to run.

**Comment by neolib** [comment]
BTW, I copied diff and cmp from git distribution and the configure scripts work fine. I guess the package may loose some meta information on what to update.

**Comment by Alexpux** [comment]
This repo for MSYS2 runtime only

**Comment by neolib** [comment]
Not sure which repo to post to, any suggestions?

**Comment by Alexpux** [comment]
MSYS2 packages. But commands are present in diffutils package.
