### ISSUE TITLE
Key 4C339812C2313FB3D3AE0C37352F52932987668A not found

### ISSUE THREAD

**Issue by IRJustman** [Alexpux/Cygwin#32]
One key, the one with ID 4C339812C2313FB3D3AE0C37352F52932987668A appears to be missing from the keyservers.  Without this key, I cannot verify downloaded packages from the repositories.

I do a pacman-key --refresh and get the following message:

$ pacman-key --refresh
gpg: refreshing 8 keys from hkp://pool.sks-keyservers.net
gpg: requesting key 2987668A from hkp server pool.sks-keyservers.net
gpg: requesting key CA25678A from hkp server pool.sks-keyservers.net
gpg: requesting key AEEA755C from hkp server pool.sks-keyservers.net
gpg: requesting key 3E0D0813 from hkp server pool.sks-keyservers.net
gpg: requesting key 3E652008 from hkp server pool.sks-keyservers.net
gpg: requesting key A47D45A1 from hkp server pool.sks-keyservers.net
gpg: requesting key 2C51581E from hkp server pool.sks-keyservers.net
gpg: requesting key 4CA56930 from hkp server pool.sks-keyservers.net
gpgkeys: key 4C339812C2313FB3D3AE0C37352F52932987668A not found on keyserver
gpg: key CA25678A: "Alexey Pavlov (Alexpux) <alexey.pawlow@gmail.com>" not changed
gpg: key AEEA755C: "Martell Malone (martell) <martellmalone@gmail.com>" not changed
gpg: key 3E0D0813: "Ray Donnelly (MSYS2 Developer - master key) <mingw.android@gmail.com>" not changed
gpg: key 3E652008: "Ignacio Casal Quinteiro <icquinteiro@gmail.com>" not changed
gpg: key A47D45A1: "Alexey Pavlov (Alexpux) <alexpux@gmail.com>" not changed
gpg: key 2C51581E: "Martell Malone (MSYS2 Developer) <martellmalone@gmail.com>" not changed
gpg: key 4CA56930: "Ray Donnelly (MSYS2 Developer) <mingw.android@gmail.com>" not changed
gpg: Total number processed: 7
gpg:              unchanged: 7
gpg: keyserver communications error: key not found
gpg: keyserver communications error: bad public key
gpg: keyserver refresh failed: bad public key
==> ERROR: A specified local key could not be updated from a keyserver.

Any suggestions?

**Comment by Alexpux** [comment]
Use appropriate repository. This one only for MSYS2 runtime itself
