### ISSUE TITLE
std::errc does not comply to C++ standard

### ISSUE THREAD

**Issue by matslil** [Alexpux/Cygwin#35]
I tried compiling following code fragment:

         throw std::system_error(make_error_code(std::errc::connection_reset),
                                 "Client socket closed");

but the compiler responds:

"error: no member named 'connection_reset' in 'std::errc'"

I've checked and rechecked the C++ standard using the following link:
   http://www.cplusplus.com/reference/system_error/errc/
and I can find this errc value, so it doesn't seem to be a spelling error.

This code compiles on my Linux machine, so I've scratched my head quite a bit about this. This is my attempt to get portable error codes working, why doesn't it work in MSYS2?

**Comment by matslil** [comment]
Seems like this is the wrong repository to report this issue on, sorry about that. If someone happens to know the repository please let me know, I'm totally confused after having searched the Internet.

**Comment by elieux** [comment]
It depends. Did you build for msys2 or for mingw-w64?

**Comment by matslil** [comment]
I was using msys2. Here are the steps I did:

1. Install msys2 (http://www.msys2.org/)
2. Open MSYS2 shell.
3. Upgrade system:
    pacman -Syu
4. Close terminal, open a new, and continue update:
    pacman -Su
5. Use "pacman" to install a number of packages:
    pacman -S make mingw-w64-x86_64-cmake mingw-w64-x86_64-clang mingw-w64-x86_64-gcc gdb
6. Create a build directory in MSYS2 environment:
    mkdir ~/build
  cd ~/build
7. Run cmake
     /mingw64/bin/cmake -G "MSYS Makefiles" /u/mlil/git/edbgserver-ng/
   or if debugging:
     /mingw64/bin/cmake -DCMAKE_BUILD_TYPE=Debug -G "MSYS Makefiles" /u/mlil/git/edbgserver-ng/
8. Run make
    make all

**Comment by elieux** [comment]
You should be running mingw64 compilations in a mingw64 shell (`msys2_shell.cmd -mingw64` or `mingw64.exe`).

The missing definitions come from libstc++-v3's [mingw32-w64/error_constants.h](https://github.com/gcc-mirror/gcc/blob/gcc-6_3_0-release/libstdc%2B%2B-v3/config/os/mingw32-w64/error_constants.h), but it seems it will be fixed in the next release (https://github.com/gcc-mirror/gcc/commit/8191163673449937e3c6bab47a069da038bf7e38).

**Comment by matslil** [comment]
Seems like it will be resolved then, thanks for the info! And thanks for correcting me about mingw64 shell!
