### ISSUE TITLE
After updating core, bash no longer echos keys in CMD and requires three keypresses per key

### ISSUE THREAD

**Issue by binki** [Alexpux/Cygwin#36]
bash runs fine in MinTTY, but I prefer to use CMD because it has a real console and doesn’t hit issues like #29. However, I ran `pacman -Syu` recently. Now when I run `bash -l` from a CMD window or directly via typing `\msys64\usr\bin\bash -l` into the Run box, I get a really weirdly behaving bash. Whenever I type a character, it does not show up in the console. To get the underlying bash to receive one character, I have to type that character three times in a row.

For example, in this session, I have typed the following:

```
eeeccchhhooo   hhhiii


eeexxxiiittt


```
(I assume I only need to hit return twice because each return is CRLF and thus two chars. Also, it’s not like I need to type the particular character three times—it’s just that bash only picks up every third character and I haven’t bothered to figure out which exact one of the three is the one getting through).

and I get the following output:
```
ohnob@DESKTOP-A4G2C0J MSYS ~
$ echo hi
hi

ohnob@DESKTOP-A4G2C0J MSYS ~
$ exit
logout

```

but while I am typing each command, nothing is echoed back to me.

Also, features like reverse-i-search (C-r) work but I have to press that shortcut multiple times and in the interactive typing each char multiple times.

I’m running with msys2-runtime-2.7.0-1, bash-4.4.012-1 x86_64 on Windows 10.0.16193.1001. The same version works fine inside of CMD on Windows 6.3.9600. I’m not sure how to go about debugging this. Please let me know if I can provide further information.

**Comment by elieux** [comment]
> I’m running with msys2-runtime-2.7.0-1, bash-4.4.012-1 x86_64 on Windows 10.0.16193.1001. The same version works fine inside of CMD on Windows 6.3.9600. I’m not sure how to go about debugging this. Please let me know if I can provide further information.

It seems that it's an incompatibility with the latest Insider build. Can you check if latest Cygwin suffers from the same issue? If not, the next step would probably be for us to update msys2-runtime to 2.8.x and try if that works.

**Comment by binki** [comment]
Yeah, I have the same problem with the latest cygwin install (from installing the `setup-x86_64.exe` from their homepage). It seems to be a combination of Windows update and recent Cygwin changes, though, as the version of bash/core that comes with the MSYS2 installer works fine still.

**Comment by elieux** [comment]
I don't have this build currently available. Could you test something for me, @binki?

1] Can you try if `cat` exhibits the same behaviour?

2] Can you try if anything changes if you run `stty raw` (both in `cat` and `bash`)?

**Comment by binki** [comment]
> I don't have this build currently available.

Oh, btw, I got upgraded further to 10.0.16199.1000 and the behavior still persists. I still am using MinTTY as a workaround to get a usable shell.

> 1] Can you try if `cat` exhibits the same behavior?

If I run `cat` from a new CMD session directly, I get the behavior I expect. Text I enter is immediately echoed by the terminal and cat echoes back each line after I hit enter. So I get the same behavior as on Linux.

If I launch `cat` from a messed up bash (by typing `cccaaattt<ret><ret><ret>`), `cat` itself runs just fine and as expected. It lets me edit a line of input at a time interactively and I see cat’s echo back when I press `<ret> once.

> 2] Can you try if anything changes if you run `stty raw` (both in `cat` and `bash`)?

From within bash, it gives an error message and that very `bash` session continues running in the weird mode where I have to type each char 3 times and I get no echo until after I hit `<ret>` three times.

```
ohnob@DESKTOP-A4G2C0J MSYS ~
$ stty raw
stty: 'standard input': unable to perform all requested operations
```

If I subsequently run `cat` after `ssty` completes, I start seeing something that looks more like raw mode. Every character I type into `cat` gets echoed back to me immediately. If I type `asdf`, I see `aassddff`. If I press `<ret>`, it moves the cursor to the beginning of the line and I type over top of what I already see (it doesn’t seem to get a line feed but does get a carriage return). If I exit `cat` (I have to kill it via Task Manager because raw mode prevents it from interpreting `C-z` or `C-c`), I get returned to the bash shell which requires typing each char three times and does not echo until after a line break. If I invoke a bash from that shell it behaves like the parent bash requiring me to type each char three times.

Given the error from stty, I thought I’d try running it as Administrator but I got the same error.

Please let me know if I followed your instructions properly. Is this different behavior between utilities expected because of some reason like “`cat` is compiled against the old version of stuff or is ported differently”?

**Comment by elieux** [comment]
> Please let me know if I followed your instructions properly.

This is excellent, thank you.

> Is this different behavior between utilities expected because of some reason like “`cat` is compiled against the old version of stuff or is ported differently”?

I chose Cat because uses a different, less involved way to read from the terminal. Bash uses Readline and Ncurses, each of which could be a factor in what we're seeing. The `stty raw` error seems to be normal though, I see it in a Conhost window as well.

I've got another task for you, if you're okay with it. Could you test how Dash performs? You might have to start it directly (i.e. not inside Bash).

**Comment by binki** [comment]
> Could you test how Dash performs?

I started `dash` directly from the Start box and from an existing CMD using `\msys64\usr\bin\dash -l` and from within bash using `dash -l` (but with typing each char three times). In all three cases, `dash` itself responds to input as expected. It doesn’t seem to support all of the libreadline emacs-like line editing shortcuts as well as libreadline, but I’m pretty sure I recall dash failing at that on Linux too ;-).

Let me know if there’s anything else for me to test to further narrow it down. Unfortunately, I do not expect to get anywhere with trying to debug/patch ncurses or libreadline myself xD.

**Comment by elieux** [comment]
Cool, so it's probably in either of those libraries. You could check:

- `mc` for Ncurses
- `sqlite` for Readline

**Comment by binki** [comment]
`sqlite` is quite usable. `mc` seems to both have trouble rendering things in the right places and possibly accepting input. The output is so messed up I can’t tell when it’s seeing key presses.

I know in the Insider blog they mentioned improving VTxxx compatibility for use with the Linux subsystem for Windows. I assume it’s somehow related to this. Maybe the new behavior causes ncurses to misdetect the terminal or it uses hacks for Windows which no longer work with the CMD behavior. Sounds like something that would be a lot of work to fix. I wonder if I can figure out how to tell ncurses that I’m using a dumb terminal or tell it to target xterm or something and see if that helps.

**Comment by elieux** [comment]
Yeah, I forgot that MC doesn't always like Conhost. Try:

- `TERM=ansi-nt mc` -- I'm able to write a command there (but not much else)
- `TERM=ntconsole mc`, `TERM=pcansi mc` -- seems to work except F<n> keys
- `LANG=en_US mc` -- seems to work best (I have `en_US.UTF-8` as default and it has issues for some reason)

You can also try reverting back to the pre-Win10 Conhost mode, see [the last screenshot in this article](https://blogs.windows.com/buildingapps/2014/10/07/console-improvements-in-the-windows-10-technical-preview/).

**Comment by elieux** [comment]
Can you also try `export`ing some of those variables to see if that helps Bash?

**Comment by binki** [comment]
@elieux with all of those options with `mc`, it seems to still have the same problem. `mc` is worse than `bash`. When it loads, it actually waits for me to press keys before it continues spinning the “loading” spinner (the `/` `-` `\` `|` thing) or before redrawing the screen. It’s like it thinks it is supposed to get responses from the VT but it ends up that the VT doesn’t respond but instead send my key presses. In `mc`, it also seems like it wants more than 3 key presses sometimes. All I manage to do is type `exit`. At least I kind of get per-character echos in `mc`.

With bash, hmm… none of those `TERM` settings seems to make a difference.

> You can also try reverting back to the pre-Win10 Conhost mode, see [the last screenshot in this article](https://blogs.windows.com/buildingapps/2014/10/07/console-improvements-in-the-windows-10-technical-preview/).

I don’t have an “Experimental” tab in the properties. That looks like it’s for when Windows 10 was still in beta, especially given the article date. The changes I think I got are described [in this blog post](https://blogs.msdn.microsoft.com/commandline/2017/04/11/windows-10-creators-update-whats-new-in-bashwsl-windows-console/).

**Comment by elieux** [comment]
> I don’t have an “Experimental” tab in the properties.

Sorry. The setting's moved. It should be on first page (Options), called "Use legacy console" ([illustration](https://www.isunshare.com/images/article/windows-10/enable-use-legacy-console-for-command-prompt-in-windows-10/select-use-legacy-console-in-options.png)).

**Comment by Alchiadus** [comment]
Hitting the same issue on `Microsoft Windows [Version 10.0.16193.1001]`.

The following workaround restored the old behaviour:
1. Open Command Prompt
2. Right-click Title Bar -> Properties
3. Tick 'Use legacy console'
4. Relaunch the console

Not sure if it is relevant, but the checkbox links to a [TechNet article](https://technet.microsoft.com/library/mt427362.aspx) which seems to describe some of the console host changes.

**Comment by binki** [comment]
Ah, sorry. Yeah, that workaround works for me too.

**Comment by yyjdelete** [comment]
Seems already fixed in win10(16215 Insider).

**Comment by binki** [comment]
Yeah, I got on build 16215 and bash works again for me.

**Comment by elieux** [comment]
Great. @Alexpux, please close the issue.
