### ISSUE TITLE
Allow overriding turning /c into c:

### ISSUE THREAD

**Issue by cool-RR** [Alexpux/Cygwin#42]
I'm not sure that I'm opening this bug on the right repo, so if I'm wrong, please direct me the right way.

I'm using the Bash shell provided by MSYS2 on Windows. I noticed that when I type a path like `/c/whatever/file.jpg` , it automatically converts it to `c:\whatever\file.jpg` . That's great, but sometimes I need to turn this convenience off. Examples: `cipher /w:C` or `cmd /c tasklist` or any Windows command that likes to take flags with slashes.

Is there a way to turn this feature off when needed?

**Comment by mingwandroid** [comment]
Please read about MSYS2_ARG_CONV_EXCL at https://github.com/msys2/msys2/wiki/Porting
